CREATE TABLE IF NOT EXISTS Image ( id BIGSERIAL PRIMARY KEY, url VARCHAR(255), duration INT, added_on TIMESTAMP, slideshow_id BIGINT NOT NULL );
CREATE TABLE IF NOT EXISTS Slideshow ( id BIGSERIAL PRIMARY KEY, total_duration BIGINT );
CREATE TABLE IF NOT EXISTS ProofOfPlay ( id BIGSERIAL PRIMARY KEY, image_id BIGINT NOT NULL , slideshow_id BIGINT NOT NULL , played_on TIMESTAMP );